export const PRODUCTS = [
  {
    id: 'silkskin-serum',
    name: 'Suero SilkSkin',
    price: 48.0,
    oldPrice: 60.0,
    image: 'resources/suero-silkSkin/belle-beauty-JPvy3rrWSeM-unsplash.jpg',
    rating: 4.8,
    category: 'skin-care',
    sizes: ['30ml', '60ml', '80ml', '100ml'],
    badge: '20% OFF',
    inStock: true,
    isBestSeller: true,
    onSale: true,
  },
  {
    id: 'argan-glow',
    name: 'Aceite Facial Argan Glow',
    price: 35.0,
    oldPrice: 42.0,
    image:
      'resources/aceite-facial-argan/elsa-olofsson-wd4FU4S8yqs-unsplash.jpg',
    rating: 4.6,
    category: 'skin-care',
    sizes: ['30ml', '50ml'],
    badge: '15% OFF',
    inStock: true,
    onSale: true,
  },
  {
    id: 'smooth-foundation',
    name: 'Base Suave',
    price: 28.0,
    image: 'resources/base-suave/birgith-roosipuu-Pd5JqHgT2Fs-unsplash.jpg',
    rating: 4.4,
    category: 'makeup',
    inStock: true,
    isNew: true,
  },
  {
    id: 'oceanmist-moisturizer',
    name: 'Hidratante OceanMist',
    price: 32.0,
    oldPrice: 38.0,
    image:
      'resources/hidratante-oceanMist/collins-lesulie-7lFGxDph5KQ-unsplash.jpg',
    rating: 4.7,
    category: 'skin-care',
    sizes: ['50ml', '100ml'],
    badge: '15% OFF',
    inStock: true,
    onSale: true,
  },
  {
    id: 'vitamin-c-serum',
    name: 'Suero Iluminador Vitamina C',
    price: 42.0,
    image:
      'resources/suero-iluminador-vitaminaC/tamara-harhai-jYifNBo1j4Y-unsplash.jpg',
    rating: 4.9,
    category: 'skin-care',
    sizes: ['30ml', '60ml'],
    inStock: true,
    isBestSeller: true,
  },
  {
    id: 'matte-lipstick',
    name: 'Colección de Labiales Mate',
    price: 18.0,
    image:
      'resources/coleccion-labiales-mate/ashley-piszek-L1iTsUBZYDk-unsplash.jpg',
    rating: 4.3,
    category: 'makeup',
    inStock: true,
  },
];
